---
- name: Compile Icecast KH
  command: "{{ item }}"
  args:
    chdir: "{{ icecastkh_tmpfile }}"
  with_items:
    - cd {{ icecastkh_tmpfile.path }} 
    - ./configure
    - make
    - make install
