---
- include_role:
    name: cmprescott.xml

- name: icecast location
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/location
    value: "{{ icecastkh_xml_location }}"

- name: icecast max clients
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/clients
    value: "{{ icecastkh_xml_clients }}"


- name: xml /icecast/limits/sources
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/clients
    value: "{{ icecastkh_xml_sources }}"

# LIMITS

- name: xml /icecast/limits/queue-size
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/queue-size
    value: "{{ icecastkh_xml_queue_size }}"

- name: xml /icecast/limits/client-timeout
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/client-timeout
    value: "{{ icecastkh_xml_client_timeout }}"

- name: xml /icecast/limits/header-timeout
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/header-timeout
    value: "{{ icecastkh_xml_header_timeout }}"

- name: xml /icecast/limits/source-timeout
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/source-timeout
    value: "{{ icecastkh_xml_source_timeout }}"

- name: xml /icecast/limits/burst-size
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/burst-size
    value: "{{ icecastkh_xml_burst_size }}"

- name: xml /icecast/limits/max-bandwidth
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/limits/max-bandwidth
    value: "{{ icecastkh_xml_max_bandwidth }}"

# AUTHENTICATION

- name: xml /icecast/authentication/source-password
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/authentication/source-password
    value: "{{ icecastkh_xml_source_password }}"

- name: xml /icecast/authentication/relay-password
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/authentication/relay-password
    value: "{{ icecastkh_xml_relay_password }}"

- name: xml /icecast/authentication/admin-user
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/authentication/admin-user
    value: "{{ icecastkh_xml_admin_user }}"

- name: xml /icecast/authentication/admin-password
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/authentication/admin-password
    value: "{{ icecastkh_xml_admin_password }}"

# LISTEN SOCKET

- name: xml /icecast/listen-socket/port
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/listen-socket/port
    value: "{{ icecastkh_xml_port }}"

# PATHS

- name: xml /icecast/paths/logdir
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/paths/logdir
    value: "{{ icecastkh_xml_logdir }}"

# LOGGIN

- name: xml /icecast/logging/accesslog
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/logging/accesslog
    value: "{{ icecastkh_xml_accesslog }}"

- name: xml /icecast/logging/errorlog
  xml:
    path: "{{ icecastkh_xml }}"
    xpath: /icecast/logging/errorlog
    value: "{{ icecastkh_xml_errorlog }}"

# MOUNTS

- name: insert/update mount
  blockinfile:
    path: "{{ icecastkh_xml }}"
    marker: "<!--  {mark} ANSIBLE MANAGED MOUNTS {{ item.name }} -->"
    insertbefore: "</icecast>"
    block: |
          <mount>
              <mount-name>/{{ item.name }}</mount-name>
              <fallback-mount>/{{ item.fallback }}  </fallback-mount>
              <password>{{ item.password }}</password>
          </mount>
  with_items: "{{ mounts }}"
  when: mounts is defined


# REDIRECT

- name: insert/update REDIRECT
  blockinfile:
    path: "{{ icecastkh_xml }}"
    marker: "<!--  {mark} ANSIBLE MANAGED REDIRECT -->"
    insertbefore: "</icecast>"
    block: |
      <redirect>
         <host>{{ icecastkh_xml_redirect_host }}</host>
         <port>{{ icecastkh_xml_redirect_port }}</port>
      </redirect>
  when: icecastkh_xml_redirect_host is defined




  - name: insert/update relay master server
    blockinfile:
      path: "{{ icecastkh_xml }}"
      marker: "<!--  {mark} ANSIBLE MANAGED relay master server -->"
      insertbefore: "</icecast>"
      block: |
        <master-server>{{ icecastkh_xml_relay_master_host }}</master-server>
        <master-server-port>{{ icecastkh_xml_relay_master_port }}</master-server-port>
        <master-update-interval>{{ icecastkh_xml_relay_master_update_interval }}</master-update-interval>
        <master-password>{{ icecastkh_xml_relay_master_password }}</master-password>
    when: icecastkh_xml_relay_master_host is defined






# FIXES

- name: Create logs folder  created
  file:
    path: "{{ icecastkh_xml_logdir }}"
    state: directory
    owner: "{{ icecastkh_xml_owner }}"
    group: "{{ icecastkh_xml_group }}"

- name: create error and access log
  file:
    path: "{{ icecastkh_xml_logdir }}/{{ icecastkh_xml_accesslog }}"
    state: touch
    owner: "{{ icecastkh_xml_owner }}"
    group: "{{ icecastkh_xml_group }}"

# RELOAD

 - name: Reload service
   shell: /etc/init.d/icecast force-reload
